## Simple Linear Regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
# Step1: Read the dataset
df=pd.read_csv('height-weight.csv')
df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [3]:
plt.scatter(df['Weight'],df['Height'])
plt.xlabel("Weight")
plt.ylabel("Height")

Text(0, 0.5, 'Height')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  23 non-null     int64
 1   Height  23 non-null     int64
dtypes: int64(2)
memory usage: 500.0 bytes

In [5]:
df.describe()

           Weight      Height
count   23.000000   23.000000
mean    73.826087  158.391304
std     17.872407   19.511626
min     45.000000  120.000000
25%     59.000000  142.500000
50%     78.000000  162.000000
75%     86.000000  175.000000
max    105.000000  183.000000

In [6]:
df.isnull().sum()

Weight    0
Height    0
dtype: int64

In [7]:
## divvide our dataset into independent and dependent features
X=df[['Weight']] ## idnependent feature
y=df['Height'] ##dependent features

In [8]:
X.shape,y.shape

((23, 1), (23,))

In [9]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=24)

In [11]:
X_train.shape,X_test.shape

((18, 1), (5, 1))

In [12]:
y_train.shape,y_test.shape

((18,), (5,))

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler=StandardScaler()

In [15]:
X_train=scaler.fit_transform(X_train)

In [16]:
X_test=scaler.transform(X_test)

In [17]:
X_test

array([[ 0.21043706],
       [ 0.21043706],
       [-1.6552288 ],
       [ 1.17153765],
       [-0.52452222]])

In [18]:
plt.scatter(X_train,y_train)

In [ ]:
scaler.transform([[80]])

In [20]:
## Model Training

from sklearn.linear_model import LinearRegression

In [21]:
regressor=LinearRegression()

In [22]:
## Training the train data
regressor.fit(X_train,y_train)

LinearRegression()

In [23]:
regressor.intercept_

157.5

In [24]:
regressor.coef_

array([17.03440872])

In [25]:
plt.scatter(X_train,y_train)
plt.plot(X_train,regressor.predict(X_train),'r')

### prediction of train data
1. predicted height output= intercept +coef_(Weights)
2. y_pred_train =157.5 + 17.03(X_train)
          
### prediction of test data
1. predicted height output= intercept +coef_(Weights)
2. y_pred_test =157.5 + 17.03(X_test)

In [26]:
## Prediction for test data
y_pred_test=regressor.predict(X_test)

In [27]:
y_pred_test

array([161.08467086, 161.08467086, 129.3041561 , 177.45645118,
       148.56507414])

In [28]:
y_test

15    177
9     170
0     120
8     182
17    159
Name: Height, dtype: int64

## Performance Metrics MAE,MSE,RMSE

In [29]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [30]:
mse=mean_squared_error(y_test,y_pred_test)
mae=mean_absolute_error(y_test,y_pred_test)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

109.77592599051664
9.822657814519232
10.477400726827081

## Accuracy of the model R squared and Adjusted r ssquared
## R square
Formula

**R^2 = 1 - SSR/SST**


- R^2	=	Accuracy of the model
- SSR	=	sum of squares of residuals
- SST	=	total sum of squares

In [31]:
from sklearn.metrics import r2_score

In [32]:
score=r2_score(y_test,y_pred_test)
score

0.776986986042344

## Adjusted r square
**Adjusted R2 = 1 – [(1-R2)*(n-1)/(n-k-1)]**

where:

- R2: The R2 of the model
- n: The number of observations
- k: The number of predictor variables

In [33]:
#display adjusted R-squared
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.7026493147231252

In [34]:
scaler

StandardScaler()

In [35]:
regressor

LinearRegression()

In [50]:
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=42)

In [51]:
X_train

    Weight
12     105
1       58
13     100
5       78
2       48
11      95
20      45
3       60
4       70
18      76
16      50
21      56
22      72
7       90
10      82
14      85
19      87
6       80

In [52]:
X_test

    Weight
15      78
9       78
0       45
8       95
17      65